### ISSUE TITLE
Incorrect escaping in where filter

### ISSUE THREAD

**Issue by maicol07** [illarionov/igdbclient#31]
Hi,
I've found out the query builder incorrectly escapes the where filter when there is a string after the `=`. For example:
```kotlin
val response = IGDBClient.getCompanies {
    fields(
        "slug",
        "published.name",
        "published.cover.image_id",
        "published.first_release_date"
    )
    where("slug = \"my-slug\"")
    limit(1)
}
```

This is translated into:
```apicalypse
f slug,published.name,published.cover.image_id,published.first_release_date;w slug = \"my-slug\";l 1;
```
(notice the escaped quotes)

and IGDB gives a 400 error:
```json
[
    {
        "title": "Syntax Error",
        "status": 400,
        "cause": "Mismatched input, double check your input. Common cause is sending \\\" instead of \"."
    }
]
```

Can you fix this?
Thanks

**Comment by illarionov** [comment]
Thank you for your interest and submitting this bug report!
I removed the escaping of the where - statement.
The fix will be available in version 0.2 (already sent for release and should be available soon)
